'use client'

import "./globals.css";
import { usePathname } from 'next/navigation';
import NavBar from "./components/navbar/navbar";
import Footer from "./components/footer/footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="scrollbar-hide flex flex-col justify-between min-h-screen">
        <NavBar />
        {children}
        <Footer className="bottom-0" />
      </body>
    </html>
  );
}
