'use client'

import "./globals.css";
import { usePathname } from 'next/navigation';
import Footer from "./components/footer/footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body className={`scrollbar-hide flex flex-col min-h-screen ${pathname == "/contact" ? "justify-center" : ""}`}>
        {children}
        {/* {pathname !== "/contact" && pathname !== "/about" && <Footer className="bottom-0" />} */}
        <Footer className="bottom-0" />
      </body>
    </html>
  );
}
